### PR TITLE
install systemd service to /etc, give sysctl numeric prefix

### PR DESCRIPTION
**Pull request by sielicki**

### CODE REVIEW

**Comment by sielicki** [comment]
I don't know enough about FHS to know whether or not the sysctl ought to go in /etc as well. Seems like that's where other packages put theirs. Here's another force push where that's done as well.

**Comment by guruofquality** [comment]
Packages in /etc are not owned by the package manager, packages in /usr/ are: https://unix.stackexchange.com/questions/206315/whats-the-difference-between-usr-lib-systemd-system-and-etc-systemd-system

If that doesnt work, the patch needs a cmake variable like SYSTEMD_DIR that defaults to "lib/systemd/system" but can be overridden

**Comment by sielicki** [comment]
```
systemd and sysctl cmake changes

* by default, don't install systemd unit on systems other than linux.
* attempt to detect systemd install directory via pkg-config
  * if not available, default to upstream systemd default rather than
    attempting to enumerate every distro under the sun.
* by default, don't change the behavior of user's kernel with sysctl.
```

**Comment by guruofquality** [comment]
The changes are basically in master, you have variables to control everything. And the default directory is /lib for package builds. Hopefully that does it. Lets let the package maintainer guys figure it out if they have problems.

**Comment by sielicki** [comment]
Works for me. Thanks.

**Pull request closed without merging**
